# tex template from https://www.overleaf.com/latex/templates/quantum-hall-effect-report-template/hqsgsyxsvphs#
# yum install tex-todonotes
FNAME="report"
run:
	pdflatex $(FNAME).tex

clean:
	rm -f $(FNAME).aux $(FNAME).log
